CXX = g++
CXXFLAGS = -std=c++17 -fprofile-arcs -ftest-coverage -I/usr/include/gtest
LDFLAGS = -lgtest -lgtest_main -pthread

all:
	$(CXX) $(CXXFLAGS) main.cpp $(LDFLAGS) -o program.out

clean:
	rm -f program.out *.gcno *.gcda coverage.info
